### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by dnmacdon** [brainhack-school2020/dnmacdon_ASD_multisite_smri#1]
@surchs Should I be including citations for each of the libraries that I mention in README.md?

**Comment by surchs** [comment]
This is a good idea. I'd say that including a link to the repositories you want to use in your Readme file might be more helpful here. For any reports that come out of your work later, you should definitely cite the libraries used to do your analyses.

**Comment by dnmacdon** [comment]
Perfect, that makes sense.
